default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: pass
  pool: 5

development:
  <<: *default
  database: todo-gamified-backend_development


test:
  <<: *default
  database: todo-gamified-backend_test